import unittest
from test_mathfun import TestMathFun
from HTMLTestRunner import HTMLTestRunner 

if __name__ == "__main__":
    suite = unittest.TestSuite()
    # tests = [TestMathFun("test_add"),TestMathFun("test_minus"),TestMathFun("test_divide")]
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFun))
    # suite.addTests(tests)

    with open("HTMLReport.html","w",encoding="utf-8") as f:
        runner = HTMLTestRunner(stream=f,
                                title = "MathFun Test Report",
                                description="generated by HTMLTestRunner.",
                                verbosity=2)

        runner.run(suite)